<?xml version="1.0" standalone="yes"?>
<!DOCTYPE zedTestMap [
<!ELEMENT testDesc (#PCDATA)*>
<!ELEMENT appliesToFile (#PCDATA)*>
<!ELEMENT specRef EMPTY>
<!ATTLIST specRef href CDATA #REQUIRED>
<!ELEMENT category (((category|test))*)>
<!ATTLIST category name CDATA #REQUIRED>
<!ELEMENT appliesToDtbType (#PCDATA)*>
<!ELEMENT msg (#PCDATA)*>
<!ATTLIST msg class (long|short) #REQUIRED>
<!ELEMENT zedTestMap ((category)+)>
<!ATTLIST zedTestMap version CDATA #REQUIRED>
<!ATTLIST zedTestMap date CDATA #REQUIRED>
<!ELEMENT onFalseMsg ((msg)*)>
<!ELEMENT comment (#PCDATA)*>
<!ELEMENT test (testDesc,appliesToFile,(appliesToDtbType)*,specRef,onFalseMsg,(comment)?)>
<!ATTLIST test id ID #REQUIRED>
<!ATTLIST test type (requirement|recommendation|strongRecommendation) #REQUIRED>
<!-- <!ENTITY extensions SYSTEM "file:///C:/Documents and Settings/jwp/My Documents/Work/ZedVal/src/zedsuite/maps/testMapExtensions.xml"> -->
]>
<zedTestMap version="1.1.0" date="2005-04-14">
<!--
** Begin description of testMap grammar **
The category element
  ELEMENT category
    The category element is a wrapper of test elements.
    It is an arbitrary wrapper; not for use by machines.
  ATTRIBUTE name
    Some descriptor string for human consumption.

The test element
  ELEMENT test
    constitutes the atomic level of the test map.
  ATTRIBUTE id
    unique identifier of this test in the test map.
    Note that in the case of test failure,
    the Zedval report will return a referenc to this value.
  ATTRIBUTE type
    Identifies the type of specification requirement.
    ENUM ('requirement'|'recommendation'|'strongRecommendation')

The testDesc element
  ELEMENT testDesc
    Plain statement of specification requirement,
    answerable only by true or false.
    If false means that specification requirement was not met.

The appliesToFile element
  ELEMENT appliesToFile
    Identifies which document/file types of the Z39.86 that this test applies to.
    Even in relational (interdocument) tests, there is only one appliesToFile element.
    Multidirectional dependencies are made unidirectional by splitting into two or more tests.

The appliesToDtbType element
  ELEMENT appliesToDtbType
    Contains the name of the DTB type that this test applies to.
    Value can be either one of the strings allowed for Z3986 dtb:multimediaType element, or a sum:
    ENUM ('audioOnly' | 'audioNCX' | 'audioPartText' | 'audioFullText' | 'textPartAudio' | 'textNCX' | 'all')

The specRef element
  ELEMENT specRef
    URI. Reference to normative statement that has been used as basis for including the test.

The onFalseMsg element
  ELEMENT onFalseMsg
    empty
  ELEMENT msg
    message to return if test returns false (normative reference was not met)
  ATTRIBUTE class
    ENUM ('long'|'short')

The comment element
  ELEMENT comment
    Arbitrary comment field for developers.

** End description of testMap grammar: **
-->
	<category name="opf">
		<category name="opf_integrity">
			<test id="opf_exists" type="requirement">
				<testDesc>package file exists</testDesc>
				<appliesToFile>opf</appliesToFile>
				<appliesToDtbType>all</appliesToDtbType>
				<specRef href="z3986.html#para_34"/>
				<onFalseMsg>
					<msg class="long">Package file does not exist</msg>
					<msg class="short">opf not found</msg>
				</onFalseMsg>
				<comment>This test is practically redundant since the application will take opf path as input param and not continue unless existing. [TN5]</comment>
			</test>
			<!-- From NLS: Q:"TN5. Only one opf file exists.
      This requires that all files for a given DTB exist in a separate directory.
      Is that a reasonable requirement, in order for the validator to work?"
      A: There is as far as we know no restriction that only one opf can exist in a given directory,
      nor does the validator depend on this since the full path to the opf is taken as an input parameter.
      -->
			<test id="opf_isReadable" type="requirement">
				<testDesc>package file is readable</testDesc>
				<appliesToFile>opf</appliesToFile>
				<appliesToDtbType>all</appliesToDtbType>
				<specRef href="z3986.html#para_34"/>
				<onFalseMsg>
					<msg class="long">Package file is not readable</msg>
					<msg class="short">opf not readable</msg>
				</onFalseMsg>
				<comment>[TN5]</comment>
			</test>
			<test id="opf_fileExtn" type="requirement">
				<testDesc>package file has .opf extension</testDesc>
				<appliesToFile>opf</appliesToFile>
				<appliesToDtbType>all</appliesToDtbType>
				<specRef href="z3986.html#para_34"/>
				<onFalseMsg>
					<msg class="long">package file does not have an .opf extension.</msg>
					<msg class="short">invalid extension</msg>
				</onFalseMsg>
				<comment>??</comment>
			</test>
		</category>
		<category name="opf_internal">
			<test id="opf_prologPubId" type="requirement">
				<testDesc>package file public identifier equals "+//ISBN 0-9673008-1-9//DTD OEB 1.0.1 Package//EN"</testDesc>
				<appliesToFile>opf</appliesToFile>
				<appliesToDtbType>all</appliesToDtbType>
				<specRef href="z3986.html#h3_13"/>
				<onFalseMsg>
					<msg class="long">package file public identifier does not equal "+//ISBN 0-9673008-1-9//DTD OEB 1.0.1 Package//EN"</msg>
					<msg class="short">public identifier value</msg>
				</onFalseMsg>
				<comment/>
			</test>
			<test id="opf_isDtdValid" type="requirement">
				<testDesc>package file is valid to DTD</testDesc>
				<appliesToFile>opf</appliesToFile>
				<appliesToDtbType>all</appliesToDtbType>
				<specRef href="z3986.html#para_34"/>
				<onFalseMsg>
					<msg class="long">package file is not valid to DTD</msg>
					<msg class="short">invalid to dtd</msg>
				</onFalseMsg>
				<comment>[TN5]</comment>
			</test>
			<category name="opf_metadata">
				<category name="dcmeta">
					<test id="opf_DcDcNamespace" type="requirement">
						<testDesc>dc-metadata has an attribute of xmlns:dc="http://purl.org/dc/elements/1.0/"</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#para_45"/>
						<onFalseMsg>
							<msg class="long">Attribute xmlns:dc="http://purl.org/dc/elements/1.0/" missing from dc-metadata element.</msg>
							<msg class="short">xmlns:dc attr</msg>
						</onFalseMsg>
						<comment>Although the oebpkg101.dtd declares this as fixed, the oeb spec states it must be physically there, hence dtd validation does not suffice [TN15]</comment>
					</test>
					<test id="opf_DcOebNamespace" type="requirement">
						<testDesc>dc-metadata has an attribute of xmlns:oebpackage="http://openebook.org/namespaces/oeb-package/1.0/"</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#para_45"/>
						<onFalseMsg>
							<msg class="long">Attribute xmlns:oebpackage="http://openebook.org/namespaces/oeb-package/1.0/" missing from dc-metadata element.</msg>
							<msg class="short">xmlns:oebpackage attr</msg>
						</onFalseMsg>
						<comment>[TN15]</comment>
					</test>
					<!-- From NLS. This test is covered by DTD
       TN9
	<test id="" type="requirement">
    		<testDesc>Unique-identifier attribute on package element exists</testDesc>
    		<appliesToFile>opf</appliesToFile>
    		<specRef href="z3986.html#para_37" />
    		<tool type="" uses="" />
    		<onFalseMsg>
      		<msg class="long">Unique-identifier attribute on package element is missing.</msg>
      		<msg class="short">unique-identifier attribute missing</msg>
    		</onFalseMsg>
	</test>
	-->
					<test id="opf_DcIdUniqIdref" type="requirement">
						<testDesc>dc:Identifier id attribute matches the value of unique-identifier attribute</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#para_37"/>
						<onFalseMsg>
							<msg class="long">Value of unique-identifier attribute on package element does not match id value of any dc:Identifier.</msg>
							<msg class="short">unique-identifier doesn't match any dc:Identifier</msg>
						</onFalseMsg>
						<comment>[TN9]</comment>
					</test>
					<test id="opf_DcIdentifierValue" type="requirement">
						<testDesc>dc:Identifier contains a value</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_181"/>
						<onFalseMsg>
							<msg class="long">dc:Identifier is not valued</msg>
							<msg class="short">dc:Identifier not valued</msg>
						</onFalseMsg>
						<comment>[TN22]</comment>
					</test>
					<!-- From NLS. This test is covered by DTD - dupe id will be reported
	<test id="" type="requirement">
    	<testDesc caseSens="CS"> id attribute of exactly one dc:Identifier element matches the value of unique-identifier attribute on package element</testDesc>
    	<appliesToFile primary="">opf</appliesToFile>
    	<specRef href="z3986.html#para_37" />
    	<tool type="" uses="" />
    	<onFalseMsg>
      	<msg class="long">id attribute of more than one dc:Identifier element matches the value of unique-identifier attribute on package element</msg>
      	<msg class="short">multiple matches between  dc:Identifier id and unique-identifier</msg>
      	</onFalseMsg>
	</test>
	-->
					<test id="opf_DcTitleValue" type="requirement">
						<testDesc>dc:Title contains a value</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_146"/>
						<onFalseMsg>
							<msg class="long">dc:Title is not valued</msg>
							<msg class="short">dc:Title not valued</msg>
						</onFalseMsg>
						<comment>is this really required by the spec?[TN16]</comment>
					</test>
					<test id="opf_DcPubPresent" type="requirement">
						<testDesc>dc:Publisher is present at least once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_161"/>
						<onFalseMsg>
							<msg class="long">dc:Publisher is missing.</msg>
							<msg class="short">dc:Publisher missing</msg>
						</onFalseMsg>
						<comment>[TN19]</comment>
					</test>
					<test id="opf_DcPubValue" type="requirement">
						<testDesc>dc:Publisher element value is not null</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_161"/>
						<onFalseMsg>
							<msg class="long">dc:Publisher is not valued</msg>
							<msg class="short">dc:Publisher not valued</msg>
						</onFalseMsg>
						<comment>[TN19]</comment>
					</test>
					<test id="opf_DcDatePresent" type="requirement">
						<testDesc>dc:Date is present at least once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_170"/>
						<onFalseMsg>
							<msg class="long">dc:Date is missing.</msg>
							<msg class="short">dc:Date missing</msg>
						</onFalseMsg>
						<comment>[TN20]</comment>
					</test>
					<test id="opf_DcDateValue" type="requirement">
						<testDesc>dc:Date value complies with ISO8601</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_170"/>
						<onFalseMsg>
							<msg class="long">dc:Date value is not compliant with ISO8601.</msg>
							<msg class="short">dc:Date value invalid</msg>
						</onFalseMsg>
						<comment>[TN20]</comment>
					</test>
					<test id="opf_DcFormatPresent" type="requirement">
						<testDesc>dc:Format is present at least once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_178"/>
						<onFalseMsg>
							<msg class="long">dc:Format is missing</msg>
							<msg class="short">dc:Format missing</msg>
						</onFalseMsg>
						<comment>[TN21]</comment>
					</test>
					<test id="opf_DcFormatValue" type="requirement">
						<testDesc>dc:Format value is "ANSI/NISO Z39.86-2002"</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_178"/>
						<onFalseMsg>
							<msg class="long">value in dc:Format is not "ANSI/NISO Z39.86-2002"</msg>
							<msg class="short">dc:Format invalid value</msg>
						</onFalseMsg>
						<comment>[TN21]</comment>
					</test>
					<test id="opf_DcLangPresent" type="requirement">
						<testDesc>dc:Language is present at least once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_189"/>
						<onFalseMsg>
							<msg class="long">dc:Language is missing.</msg>
							<msg class="short">dc:Language missing</msg>
						</onFalseMsg>
						<comment>[TN23]</comment>
					</test>
					<test id="opf_DcLangValue" type="requirement">
						<testDesc>dc:Language value is a valid RFC 1766 code</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_189"/>
						<onFalseMsg>
							<msg class="long">value in dc:Language is not valid RFC 1766 code</msg>
							<msg class="short">dc:Language value invalid</msg>
						</onFalseMsg>
						<comment>[TN23]</comment>
					</test>
				</category>
				<!-- From NLS. This test is redundant - meta not allowed anywhere else in opf than under x-metadata ??
         TN24 Do we need to create a separate test for each of the "dtb:" names included below?
	<test id="" type="requirement">
    	<testDesc caseSens="CS">The names dtb:sourceDate, dtb:sourceEdition, dtb:sourcePublisher, dtb:sourceRights, dtb:sourceTitle, dtb:multimediaType, dtb:narrator, dtb:producer, dtb:producedDate, dtb:revision, dtb:revisionDate, dtb:revisionDescription, dtb:totalTime, and dtb:audioFormat may only appear within the x-metadata containing element, as values of the name attribute on the meta element.</testDesc>
    	<appliesToFile>opf</appliesToFile>
    	<specRef href="z3986.html#para_50" />
    	<tool type="" uses="" />
    	<onFalseMsg>
      		<msg class="long">The name dtb:??? is used in incorrect location.</msg>
      		<msg class="short">dtb:??? used in wrong location.</msg>
    	</onFalseMsg>     (???): How do you handle the different names? Just do a different test for each?
	</test>
	-->
				<category name="xmeta">
					<test id="opf_xMetaDtbSourceDatePresence" type="requirement">
						<testDesc>x-metadata element dtb:sourceDate occurs zero or once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_201"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:sourceDate occured more than one time</msg>
							<msg class="short">dtb:sourceDate ocurrence</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbSourceDateValue" type="requirement">
						<testDesc>x-metadata element dtb:sourceDate value is valid to iso8601</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_201"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:sourceDate value is not valid to iso8601</msg>
							<msg class="short">dtb:sourceDate value</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbSourceEditionPresence" type="requirement">
						<testDesc>x-metadata element dtb:sourceEdition occurs zero or once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_204"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:sourceEdition occured more than one time</msg>
							<msg class="short">dtb:sourceEdition ocurrence</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbSourcePublisherPresence" type="requirement">
						<testDesc>x-metadata element dtb:sourcePublisher occurs zero or once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_207"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:sourcePublisher occured more than one time</msg>
							<msg class="short">dtb:sourcePublisher ocurrence</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbSourceRightsPresence" type="requirement">
						<testDesc>x-metadata element dtb:sourceRights occurs zero or once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_210"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:sourceRights occured more than one time</msg>
							<msg class="short">dtb:sourceRights ocurrence</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbSourceTitlePresence" type="requirement">
						<testDesc>x-metadata element dtb:sourceTitle occurs zero or once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_213"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:sourceTitle occured more than one time</msg>
							<msg class="short">dtb:sourceTitle ocurrence</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<!-- NLS Q:"TN 31 Do we really need two tests for "exactly one occurrence of": one with onFalseMsg "x is missing,"
       and one with Msg "too many x's"?  Both are given here." A: No, test only for "exactly one". -->
					<test id="opf_xMetaMmTypePresence" type="requirement">
						<testDesc>x-metadata element dtb:multimediaType occurs exactly once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_216"/>
						<onFalseMsg>
							<msg class="long">dtb:multimediaType is missing or duplicated in x-metadata</msg>
							<msg class="short">zero or several dtb:multimediaType</msg>
						</onFalseMsg>
						<comment>[TN31]</comment>
					</test>
					<test id="opf_xMetaMmTypeValue" type="requirement">
						<testDesc>x-metadata dtb:multimediaType value is one of: audioOnly, audioNCX, audioPartText, audioFullText, textPartAudio, textNCX</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_216"/>
						<onFalseMsg>
							<msg class="long">invalid value in dtb:multimediaType</msg>
							<msg class="short">invalid dtb:multimediaType value</msg>
						</onFalseMsg>
						<comment>[TN31]</comment>
					</test>
					<test id="opf_xMetaTotTimePresence" type="requirement">
						<testDesc>x-metadata element dtb:totalTime occurs exactly once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_234"/>
						<onFalseMsg>
							<msg class="long">dtb:totalTime is missing or duplicated in x-metadata</msg>
							<msg class="short">zero or several dtb:totalTime</msg>
						</onFalseMsg>
						<comment>[TN36]</comment>
					</test>
					<test id="opf_xMetaTotTimeValue" type="requirement">
						<testDesc>x-metadata dtb:totalTime value uses valid syntax</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_234"/>
						<onFalseMsg>
							<msg class="long">Format of value in dtb:totalTime is invalid</msg>
							<msg class="short">dtb:totalTime invalid</msg>
						</onFalseMsg>
						<comment>[TN36]</comment>
					</test>
					<test id="opf_xMetaTotTimeAccurate" type="requirement">
						<testDesc>x-metadata dtb:totalTime value is the sum of the durations of all SMIL files in the spine</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_234"/>
						<onFalseMsg>
							<msg class="long">Value in dtb:totalTime does not match sum of actual durations of all SMIL files in spine</msg>
							<msg class="short">dtb:totalTime inaccurate</msg>
						</onFalseMsg>
						<comment>Added by jwpritchett, 25 Oct 2004 for version 1.0.1</comment>
					</test>
					<test id="opf_xMetaDtbProducedDatePresence" type="requirement">
						<testDesc>x-metadata element dtb:producedDate occurs zero or once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_225"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:producedDate occured more than one time</msg>
							<msg class="short">dtb:producedDate ocurrence</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbProducedDateValue" type="requirement">
						<testDesc>x-metadata element dtb:producedDate value is valid to iso8601</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_225"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:producedDate value is not valid to iso8601</msg>
							<msg class="short">dtb:producedDate value</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbRevisionPresence" type="requirement">
						<testDesc>x-metadata element dtb:revision occurs zero or once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_228"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:revision occured more than one time</msg>
							<msg class="short">dtb:revision ocurrence</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbRevisionValue" type="requirement">
						<testDesc>x-metadata element dtb:revision value is a non negative integer</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_228"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:revision value is not a non negative integer</msg>
							<msg class="short">dtb:revision value</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbRevisionDatePresence" type="requirement">
						<testDesc>x-metadata element dtb:revisionDate occurs zero or once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_231"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:revisionDate occured more than one time</msg>
							<msg class="short">dtb:revisionDate ocurrence</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbRevisionDateValue" type="requirement">
						<testDesc>x-metadata element dtb:revisionDate value is valid to iso8601</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_231"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:revisionDate value is not valid to iso8601</msg>
							<msg class="short">dtb:revisionDate value</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbRevisionDescriptionPresence" type="requirement">
						<testDesc>x-metadata element dtb:revisionDescription occurs zero or once</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_231a"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:revisionDescription occured more than one time</msg>
							<msg class="short">dtb:revisionDescription ocurrence</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbAudioFormatValue" type="requirement">
						<testDesc>x-metadata element dtb:audioFormat has allowed value</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#li_237"/>
						<onFalseMsg>
							<msg class="long">x-metadata element dtb:audioFormat value is not allowed</msg>
							<msg class="short">dtb:audioFormat value</msg>
						</onFalseMsg>
						<comment/>
					</test>
					<test id="opf_xMetaDtbPrefixRestriction" type="requirement">
						<testDesc>x-metadata meta element name attributes beginning with the prefix "dtb:" concludes with one of the following strings: sourceDate sourceEdition sourcePublisher sourceRights sourceTitle multimediaType narrator producer producedDate revision revisionDate totalTime audioFormat</testDesc>
						<appliesToFile>opf</appliesToFile>
						<appliesToDtbType>all</appliesToDtbType>
						<specRef href="z3986.html#para_50"/>
						<onFalseMsg>
							<msg class="long">metadata names may not begin with the prefix "dtb:" unless defined in Z39.86</msg>
							<msg class="short">dtb: prefix not allowed</msg>
						</onFalseMsg>
						<comment>[TN25]</comment>
					</test>
				</category>
			</category>
			<category name="opf_manifest">
				<test id="opf_mnfNcxId" type="requirement">
					<testDesc>manifest contains one item whose id value equals "ncx"</testDesc>
					<appliesToFile>opf</appliesToFile>
					<appliesToDtbType>all</appliesToDtbType>
					<specRef href="z3986.html#para_53"/>
					<onFalseMsg>
						<msg class="long">One manifest item in ncx must have id="ncx"</msg>
						<msg class="short">manifest: no ncx id value</msg>
					</onFalseMsg>
					<comment>[TN41]</comment>
				</test>
				<test id="opf_mnfOneSmil" type="requirement">
					<testDesc>manifest references at least one SMIL file</testDesc>
					<appliesToFile>opf</appliesToFile>
					<appliesToDtbType>all</appliesToDtbType>
					<specRef href="z3986.html#para_101"/>
					<onFalseMsg>
						<msg class="long">no SMIL file found</msg>
						<msg class="short">no smil</msg>
					</onFalseMsg>
				</test>
				<test id="opf_mnfOneAudio" type="requirement">
					<testDesc>manifest references at least one audio file</testDesc>
					<appliesToFile>opf</appliesToFile>
					<appliesToDtbType>audioOnly</appliesToDtbType>
					<appliesToDtbType>audioNCX</appliesToDtbType>
					<appliesToDtbType>audioPartText</appliesToDtbType>
					<appliesToDtbType>audioFullText</appliesToDtbType>
					<appliesToDtbType>textPartAudio</appliesToDtbType>
					<specRef href="z3986.html#para_101"/>
					<onFalseMsg>
						<msg class="long">no audio file found</msg>
						<msg class="short">no audio</msg>
					</onFalseMsg>
				</test>
				<test id="opf_mnfOneDtbook" type="requirement">
					<testDesc>manifest references at least one dtbook file</testDesc>
					<appliesToFile>opf</appliesToFile>
					<appliesToDtbType>audioPartText</appliesToDtbType>
					<appliesToDtbType>audioFullText</appliesToDtbType>
					<appliesToDtbType>textPartAudio</appliesToDtbType>
					<appliesToDtbType>textNCX</appliesToDtbType>
					<specRef href="z3986.html#para_101"/>
					<onFalseMsg>
						<msg class="long">no dtbook document found</msg>
						<msg class="short">no dtbook</msg>
					</onFalseMsg>
				</test>
				<test id="opf_mnfZeroDtbook" type="requirement">
					<testDesc>manifest does not reference dtbook files</testDesc>
					<appliesToFile>opf</appliesToFile>
					<appliesToDtbType>audioOnly</appliesToDtbType>
					<specRef href="z3986.html#para_101"/>
					<onFalseMsg>
						<msg class="long">dtbook document found</msg>
						<msg class="short">dtbook</msg>
					</onFalseMsg>
				</test>
				<test id="opf_mnfZeroAudio" type="requirement">
					<testDesc>manifest does not reference audio files</testDesc>
					<appliesToFile>opf</appliesToFile>
					<appliesToDtbType>textNCX</appliesToDtbType>
					<specRef href="z3986.html#para_101"/>
					<onFalseMsg>
						<msg class="long">audio file found</msg>
						<msg class="short">audio</msg>
					</onFalseMsg>
				</test>
				<test id="opf_mnfDistInfo" type="requirement">
					<testDesc>manifest does not reference a distInfo file</testDesc>
					<appliesToFile>opf</appliesToFile>
					<appliesToDtbType>all</appliesToDtbType>
					<specRef href="z3986.html#para_52"/>
					<onFalseMsg>
						<msg class="long">distInfo file listed in manifest -- not allowed</msg>
						<msg class="short">manifest: distInfo listed</msg>
					</onFalseMsg>
					<comment/>
				</test>
				<!-- Defer until ZedVal has knowledge of distinfo issues.
				<test id="opf_mnfChangeMsg" type="requirement">
					<testDesc>manifest does not reference a changeMsg file</testDesc>
					<appliesToFile>opf</appliesToFile>
					<appliesToDtbType>all</appliesToDtbType>
					<specRef href="z3986.html#para_52"/>
					<onFalseMsg>
						<msg class="long">changeMsg file listed in manifest - not allowed</msg>
						<msg class="short">manifest: changeMsg listed</msg>
					</onFalseMsg>
					<comment/>
				</test> -->
				<test id="opf_mnfHrefUri" type="requirement">
					<testDesc>item element href attribute value is a valid URI</testDesc>
					<appliesToFile>opf</appliesToFile>
					<appliesToDtbType>all</appliesToDtbType>
					<specRef href="z3986.html#para_52"/>
					<onFalseMsg>
						<msg class="long">item element href attribute value is not a valid URI</msg>
						<msg class="short">item href value</msg>
					</onFalseMsg>
					<comment/>
				</test>
				<test id="opf_mnfHrefUnique" type="requirement">
					<testDesc>item element href attribute value is unique among items</testDesc>
					<appliesToFile>opf</appliesToFile>
					<appliesToDtbType>all</appliesToDtbType>
					<specRef href="z3986.html#para_52"/>
					<onFalseMsg>
						<msg class="long">Same file listed more than once in manifest</msg>
						<msg class="short">duplicate filename in manifest</msg>
					</onFalseMsg>
					<comment/>
				</test>
				<test id="opf_mnfHrefFrag" type="requirement">